### ISSUE TITLE
identify a dev dataset from Run2.2i y01 data

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/gen3_workflow#1]

**Comment by heather999** [comment]
As outlined here: https://github.com/LSSTDESC/gen3_workflow/wiki/Development-Datasets we could start with Run2.2i Y1 tract 3828, 5 visits each from all the bands.
It might be fun to redo the ingest and confirm we can reproduce the plot.

**Comment by jchiang87** [comment]
closed by #1
