### ISSUE TITLE
Set up Postgres at NERSC using Spin

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/gen3_workflow#7]
**References**
[Postgres Docker images are available on Dockerhub](https://hub.docker.com/_/postgres) targeting version 12.4
[More documentation](https://github.com/docker-library/docs/blob/master/postgres/README.md), including details about adding extensions such as btree_gist

**Comment by JoanneBogart** [comment]
This [Ticket](https://nersc.servicenowservices.com/nav_to.do?uri=incident.do%3Fsys_id=996cca5d1b1024502548ea82f54bcbd4%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true) opened to inquire about upgrading NERSC PostgreSQL server

Johannes from NERSC Consulting suggests we look at the example recipe at 
https://github.com/NERSC/spin-recipes/tree/master/postgres

I suspect we want to use postgres:12.4-alpine  
It's not listed in the recipe as a possibility but such a thing does exist on Dockerhub

**Comment by heather999** [comment]
We have an initial Postgres DB with btree_gist set up on Spin in Rancher 1. Some things to note:
* Starting with postgres:12-4-alpine for now, with the intent of upgrading to 13 as soon as this week.
* pg_dump backups are not yet functional but should be fixed in the next couple of days, so for now, there is no backup of this db.
* We will migrate to Spin Rancher 2 in the next few months (which should be irrelevant from an end-user standpoint). We need to wait until connections other than HTTP are supported in Rancher 2. 
* While we are on Rancher 1, we should limit the postgres footprint to 100 - 200 GB. Our current desc_dm_gen3 is 4324 MB, so this should be ok for now.

To use this for gen3 processing requires:
* Creating a schema in the `desc_dm_gen3_spin` database, in the past we set up a separate schema for each DM weekly used for processing
* Updating ~/.lsst/db-auth.yaml with the appropriate credentials
* Modifying the gen3 yaml to set the datastore and registry

**Comment by jchiang87** [comment]
@heather999 Can we increase `max_connections` for the db?   See this [slack exchange](https://lsstc.slack.com/archives/C01FBUGM2CV/p1616425131112000).  A value of `max_connections = 500` was suggested.

**Comment by JoanneBogart** [comment]
@heather999  Should I look into this or will you handle it (or perhaps you already did).

**Comment by heather999** [comment]
Working on it - had a scheduled check up in between and now getting back.  I see what to update, just trying to get Rancher and I to agree that I'm updating that setting :) Might be back looking for advice!
@jchiang87 There may be some periods where the DB is unavailable as I attempt to either update this one (didn't deploy successfully the first time), or fall back and just start up a fresh instance and restore the back up from late late night (I'm assuming there's nothing in the tables since then that is an absolute disaster to lose)
Going forward this should be set up to allow more graceful upgrades..where it's mostly invisible to others.

**Comment by jchiang87** [comment]
No rush. I'm working on other things currently, and can use the non-Spin db until you're finished.

**Comment by heather999** [comment]
It's updated, max_connections is now set to 500.  Next time updates will be faster.. I had to learn about negative DNS caching.  I was too quick to check that the update was applied by trying to connect to the host..and then I was put into a 5 min penalty box.. making me think things were not accessible :)  
Still on my to do list is to transfer my notes to a Confluence page.

**Comment by jchiang87** [comment]
Using `max_connections = 500` seems to have solved the immediate connection scaling problems I saw.  If possible, I think it might be good to try setting up server-side connection pooling, i.e., with pgpool, so see if that will allow us to scale the number of concurrent jobs well past `max_connections`.   This isn't needed right away, but something to consider in the next few weeks, maybe when we move to postgres 13.

**Comment by jchiang87** [comment]
I think we now have a postgres instance that serves our needs well for Gen3 work, so closing this issue.
